name: Build

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [16]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build with Maven
        run: mvn -B package -T 2C
      - name: Archive artifacts (Geyser Standalone)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Standalone (Java ${{ matrix.java }})
          path: bootstrap/standalone/target/Geyser.jar
      - name: Archive artifacts (Geyser Spigot)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Spigot (Java ${{ matrix.java }})
          path: bootstrap/spigot/target/Geyser-Spigot.jar
      - name: Archive artifacts (Geyser BungeeCord)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser BungeeCord (Java ${{ matrix.java }})
          path: bootstrap/bungeecord/target/Geyser-BungeeCord.jar
      - name: Archive artifacts (Geyser Sponge)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Sponge (Java ${{ matrix.java }})
          path: bootstrap/sponge/target/Geyser-Sponge.jar
      - name: Archive artifacts (Geyser Velocity)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Velocity (Java ${{ matrix.java }})
          path: bootstrap/velocity/target/Geyser-Velocity.jar
      - name: Release Build
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            bootstrap/standalone/target/Geyser.jar
            bootstrap/spigot/target/Geyser-Spigot.jar
            bootstrap/bungeecord/target/Geyser-BungeeCord.jar
            bootstrap/sponge/target/Geyser-Sponge.jar
            bootstrap/velocity/target/Geyser-Velocity.jar
